//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Company()
        {
            this.Tbl_Contact = new HashSet<Tbl_Contact>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CompanyABN_CAN { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Contact> Tbl_Contact { get; set; }
    }
}
