//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contact
    {
        public int ID { get; set; }
        public byte TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool ContractType { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Department { get; set; }
    
        public virtual Tbl_Title Tbl_Title { get; set; }
    }
}
